version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '4000:4000'
    depends_on:
      - database

  database:
    image: postgres:13
    environment:
      - POSTGRES_USER=supply_chain_usr
      - POSTGRES_PASSWORD=@supply_chain_trace_usr23!
      - POSTGRES_DB=supply_chain_track
    ports:
      - '5432:5432'
